import { Template, waitForPort, waitForProcess, waitForTimeout } from 'e2b'

export const template = Template()
  .fromImage('node:21-slim')
  .setUser('root')
  .setWorkdir('/')
  .runCmd('apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*')
  .setWorkdir('/home/user/nextjs-app')
  .runCmd('npx --yes create-next-app@15.3.3 . --yes')
  .runCmd('npx --yes shadcn@2.6.3 init --yes -b neutral --force')
  .runCmd('npx --yes shadcn@2.6.3 add --all --yes')
  .runCmd('mv /home/user/nextjs-app/* /home/user/ && rm -rf /home/user/nextjs-app')
  .setUser('user')
  .setWorkdir('/home/user')
  .setStartCmd('npx next dev --turbopack', waitForPort(3000))